"""Synthetic payment stream generator with correlated behavioral and graph signals.

The generator intentionally keeps the transaction schema human-readable. This makes it
useful for a demo while preserving the important design idea: attacks are generated by
composing realistic baseline distributions with scenario-specific mutations, not by
sampling random noise around a label.
"""

from __future__ import annotations

import math
import random
import uuid
from datetime import datetime, timedelta, timezone
from typing import Iterable

from .taxonomy import ATTACKS, ATTACK_BY_ID, AttackScenario


RAILS = ("card_not_present", "card_present", "wallet", "instant_transfer", "bank_transfer", "qr")
CHANNELS = ("ecommerce", "mobile_app", "merchant_terminal", "contact_center", "email", "marketplace")
COUNTRIES = ("IN", "US", "GB", "SG", "AE", "AU")
MCCS = ("5411", "5812", "5651", "5732", "5999", "6012", "6051", "7311", "7399", "7995")


def _clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, value))


def _sigmoid(value: float) -> float:
    return 1.0 / (1.0 + math.exp(-max(-30.0, min(30.0, value))))


class SyntheticGenerator:
    """Generate legitimate and attack transactions from a seeded pseudo-random stream."""

    def __init__(self, seed: int = 2026):
        self.seed = seed
        self.rng = random.Random(seed)
        self._clock = datetime(2026, 8, 18, 7, 0, tzinfo=timezone.utc)
        self._counter = 0

    def _id(self, prefix: str) -> str:
        self._counter += 1
        return f"{prefix}-{self._counter:06d}"

    def _base(self, label: int = 0) -> dict:
        r = self.rng
        account_age = max(2, int(r.lognormvariate(5.0, 1.0)))
        device_age = max(1, int(r.lognormvariate(4.4, 1.1)))
        amount = max(2.5, r.lognormvariate(3.55, 0.78))
        hour = int((self._clock.hour + r.gauss(0, 3)) % 24)
        rail = r.choices(RAILS, weights=(36, 12, 15, 19, 9, 9))[0]
        channel = r.choices(CHANNELS, weights=(35, 18, 15, 10, 9, 13))[0]
        country = r.choices(COUNTRIES, weights=(58, 11, 9, 8, 6, 8))[0]
        tx = {
            "id": self._id("tx"),
            "timestamp": self._clock.isoformat().replace("+00:00", "Z"),
            "label": label,
            "attack_id": None,
            "rail": rail,
            "channel": channel,
            "amount": round(amount, 2),
            "currency": "INR" if country == "IN" else "USD",
            "country": country,
            "merchant_category": r.choice(MCCS),
            "merchant_id": f"m-{r.randint(100, 999):03d}",
            "customer_id": f"c-{r.randint(1000, 9999):04d}",
            "device_id": f"d-{r.randint(10000, 99999):05d}",
            "account_age_days": account_age,
            "device_age_days": device_age,
            "hour": hour,
            "distance_from_home_km": round(abs(r.gauss(9, 14)), 1),
            "velocity_10m": max(1, int(r.expovariate(0.55))),
            "velocity_1h": max(1, int(r.expovariate(0.22))),
            "new_payee": int(r.random() < 0.08),
            "credential_reset_24h": int(r.random() < 0.015),
            "biometric_confidence": round(_clamp(r.gauss(0.94, 0.05)), 3),
            "session_entropy": round(_clamp(r.gauss(0.18, 0.11)), 3),
            "typing_consistency": round(_clamp(r.gauss(0.88, 0.09)), 3),
            "ip_risk": round(_clamp(r.betavariate(2.2, 13)), 3),
            "merchant_risk": round(_clamp(r.betavariate(2.5, 10)), 3),
            "graph_mule_score": round(_clamp(r.betavariate(1.6, 18)), 3),
            "synthetic_identity_score": round(_clamp(r.betavariate(1.4, 15)), 3),
            "prompt_pressure_score": round(_clamp(r.betavariate(1.2, 16)), 3),
            "llm_similarity_score": round(_clamp(r.betavariate(1.5, 14)), 3),
            "remote_access": int(r.random() < 0.008),
            "auth_downgrade": int(r.random() < 0.01),
            "token_age_hours": round(max(0.5, r.lognormvariate(4.6, 1.2)), 2),
            "merchant_age_days": max(12, int(r.lognormvariate(6.0, 1.2))),
            "descriptor_drift": round(_clamp(r.betavariate(1.2, 16)), 3),
            "refund_velocity": round(max(0.0, r.gauss(0.08, 0.09)), 3),
            "card_present": int(rail == "card_present"),
            "tokenized": int(rail == "wallet"),
            "auth_method": r.choice(("3ds", "otp", "biometric", "passkey", "none")),
            "decision": "pending",
        }
        self._clock += timedelta(seconds=max(5, int(r.expovariate(1 / 22))))
        return tx

    def _apply_attack(self, tx: dict, attack: AttackScenario, intensity: float) -> dict:
        r = self.rng
        family = attack.family
        # Each family changes a coherent bundle of signals. Intensity is a multiplier
        # for adversarial pressure, while small noise keeps the model from keying on one rule.
        i = _clamp(intensity, 0.2, 1.5)
        def bump(key: str, amount: float, low: float = 0.0, high: float = 1.0) -> None:
            tx[key] = round(_clamp(float(tx.get(key, 0)) + amount * i + r.gauss(0, amount * 0.09), low, high), 3)

        if family in {"account_takeover", "otp_relay", "support_impersonation", "remote_access"}:
            tx["credential_reset_24h"] = int(r.random() < 0.78)
            tx["new_payee"] = int(r.random() < 0.82)
            tx["device_age_days"] = max(0, int(r.lognormvariate(1.0, 0.8)))
            bump("ip_risk", 0.36)
            bump("session_entropy", 0.4)
            bump("typing_consistency", -0.34)
            bump("prompt_pressure_score", 0.46)
            if family == "remote_access":
                tx["remote_access"] = 1
            if family == "otp_relay":
                tx["auth_method"] = "otp"
        elif family in {"authorized_push", "invoice_fraud", "social_engineering"}:
            tx["rail"] = "instant_transfer" if family == "authorized_push" else "bank_transfer"
            tx["channel"] = r.choice(("email", "contact_center", "mobile_app"))
            tx["new_payee"] = 1
            tx["amount"] = round(max(tx["amount"] * (2.2 + r.random() * 4.2) * i, 500), 2)
            bump("prompt_pressure_score", 0.62)
            bump("graph_mule_score", 0.48)
            bump("merchant_risk", 0.18)
        elif family in {"card_testing", "triangulation", "subscription_abuse"}:
            tx["rail"] = "card_not_present"
            tx["channel"] = r.choice(("ecommerce", "marketplace"))
            tx["amount"] = round(max(1.25, tx["amount"] * (0.18 + r.random() * 0.48)), 2)
            tx["velocity_10m"] = int(8 + r.random() * 18 * i)
            tx["velocity_1h"] = int(20 + r.random() * 50 * i)
            tx["device_id"] = f"swarm-{r.randint(1, 18):02d}"
            bump("ip_risk", 0.28)
            bump("session_entropy", 0.48)
            bump("merchant_risk", 0.24)
            if family == "triangulation":
                bump("graph_mule_score", 0.42)
        elif family in {"wallet_provisioning", "wallet_relay", "biometric_bypass"}:
            tx["rail"] = "wallet"
            tx["channel"] = "mobile_app" if family != "biometric_bypass" else "contact_center"
            tx["tokenized"] = 1
            tx["device_age_days"] = max(0, int(r.random() * 5))
            tx["token_age_hours"] = round(max(0.1, r.random() * 18), 2)
            tx["auth_method"] = "biometric"
            bump("biometric_confidence", -0.3)
            bump("ip_risk", 0.23)
            bump("graph_mule_score", 0.37)
            if family == "wallet_relay":
                tx["distance_from_home_km"] = round(200 + r.random() * 1600, 1)
                tx["velocity_10m"] = int(5 + r.random() * 12)
            if family == "biometric_bypass":
                tx["auth_method"] = "voice"
        elif family in {"synthetic_identity", "synthetic_supplier"}:
            tx["account_age_days"] = int(80 + r.random() * 900)
            bump("synthetic_identity_score", 0.68)
            bump("graph_mule_score", 0.44)
            bump("llm_similarity_score", 0.4)
            tx["new_payee"] = int(r.random() < 0.75)
            if family == "synthetic_supplier":
                tx["merchant_age_days"] = int(15 + r.random() * 100)
                bump("merchant_age_risk", 0.6)
                bump("descriptor_drift", 0.36)
        elif family in {"merchant_bustout", "transaction_laundering", "merchant_collusion"}:
            tx["rail"] = "card_not_present"
            tx["channel"] = "ecommerce"
            tx["merchant_age_days"] = int(4 + r.random() * 120)
            bump("merchant_age_risk", 0.62)
            bump("merchant_risk", 0.48)
            bump("descriptor_drift", 0.58)
            bump("refund_velocity", 0.42)
            bump("graph_mule_score", 0.36)
            tx["velocity_1h"] = int(18 + r.random() * 45)
            if family == "merchant_bustout":
                tx["amount"] = round(tx["amount"] * (2.1 + r.random() * 3.5), 2)
        elif family in {"refund_abuse", "chargeback_abuse"}:
            bump("refund_velocity", 0.72)
            bump("llm_similarity_score", 0.49)
            bump("prompt_pressure_score", 0.26)
            tx["velocity_1h"] = int(5 + r.random() * 16)
        elif family in {"qr_diversion", "mule_network", "payroll_diversion"}:
            tx["rail"] = "qr" if family == "qr_diversion" else "bank_transfer"
            tx["channel"] = r.choice(("mobile_app", "email", "contact_center"))
            tx["new_payee"] = 1
            bump("graph_mule_score", 0.7)
            bump("prompt_pressure_score", 0.47)
            tx["amount"] = round(max(tx["amount"] * (1.4 + r.random() * 4.0), 120), 2)
            tx["velocity_1h"] = int(4 + r.random() * 16)
        else:
            bump("merchant_risk", 0.35)
            bump("llm_similarity_score", 0.25)
            tx["new_payee"] = int(r.random() < 0.62)

        # Shared GenAI fingerprints: unusually polished interaction paired with pressure.
        bump("llm_similarity_score", 0.18)
        tx["attack_id"] = attack.id
        tx["attack_family"] = attack.family
        tx["attack_name"] = attack.name
        tx["label"] = 1
        return tx

    def generate_legitimate(self, count: int) -> list[dict]:
        return [self._base(0) for _ in range(max(0, count))]

    def generate_attacks(
        self,
        count: int,
        attack_ids: Iterable[str] | None = None,
        intensity: float = 1.0,
    ) -> list[dict]:
        ids = [item for item in (attack_ids or []) if item in ATTACK_BY_ID]
        if not ids:
            ids = [attack.id for attack in ATTACKS]
        attacks = [ATTACK_BY_ID[item] for item in ids]
        return [self._apply_attack(self._base(1), self.rng.choice(attacks), intensity) for _ in range(max(0, count))]

    def generate_mixed(self, count: int, attack_rate: float = 0.18, intensity: float = 1.0) -> list[dict]:
        attack_count = int(round(count * _clamp(attack_rate, 0.0, 1.0)))
        rows = self.generate_legitimate(count - attack_count)
        rows.extend(self.generate_attacks(attack_count, intensity=intensity))
        self.rng.shuffle(rows)
        return rows


def scenario_stats(rows: list[dict]) -> dict:
    total = len(rows)
    attacks = [row for row in rows if row.get("label") == 1]
    by_scenario: dict[str, int] = {}
    for row in attacks:
        key = row.get("attack_id") or "unknown"
        by_scenario[key] = by_scenario.get(key, 0) + 1
    return {
        "total": total,
        "attacks": len(attacks),
        "legitimate": total - len(attacks),
        "coverage": len(by_scenario),
        "by_scenario": by_scenario,
    }

